package net.atos.entng.forum.test.integration

import io.gatling.core.Predef._
import io.gatling.http.Predef._

import org.entcore.test.appregistry.Role

object ForumScenario {

	val scn =
    Role.createAndSetRole("Forum")
    .exec(http("Login 1 - teacher")
      .post("""/auth/login""")
      .formParam("""email""", """${teacherLogin}""")
      .formParam("""password""", """blipblop""")
      .check(status.is(302)))

  // Categories
  .exec(http("Category Create")
    .post("/forum/categories")
	  .body(StringBody("""{"name" : "category created"}"""))
    .check(status.is(200), 
        jsonPath("$._id").find.saveAs("categoryId")
      ))
  .exec(http("Category Get")
    .get("/forum/category/${categoryId}")
    .check(status.is(200), 
        jsonPath("$._id").find.is("${categoryId}"),
        jsonPath("$.name").find.is("category created")
      ))
  .exec(http("Category Update")
    .put("/forum/category/${categoryId}")
    .body(StringBody("""{"name" : "category updated"}"""))
    .check(status.is(200)))
  .exec(http("Category Get updated")
    .get("/forum/category/${categoryId}")
    .check(status.is(200), 
        jsonPath("$.name").find.is("category updated")
      ))
  .exec(http("Category List")
    .get("/forum/categories")
    .check(status.is(200), 
        jsonPath("$[0]._id").find.is("${categoryId}")
      ))

  // Subjects
  .exec(http("Subject Create")
    .post("/forum/category/${categoryId}/subjects")
    .body(StringBody("""{"title" : "subject created"}"""))
    .check(status.is(200), 
        jsonPath("$._id").find.saveAs("subjectId")
      ))
  .exec(http("Subject Get")
    .get("/forum/category/${categoryId}/subject/${subjectId}")
    .check(status.is(200), 
        jsonPath("$._id").find.is("${subjectId}"),
        jsonPath("$.title").find.is("subject created")
      ))
  .exec(http("Subject Update")
    .put("/forum/category/${categoryId}/subject/${subjectId}")
    .body(StringBody("""{"title" : "subject updated"}"""))
    .check(status.is(200)))
  .exec(http("Subject Get updated")
    .get("/forum/category/${categoryId}/subject/${subjectId}")
    .check(status.is(200), 
        jsonPath("$.title").find.is("subject updated")
      ))
  .exec(http("Subject List")
    .get("/forum/category/${categoryId}/subjects")
    .check(status.is(200), 
        jsonPath("$[0]._id").find.is("${subjectId}")
      ))

  // Messages
  .exec(http("Message Create")
    .post("/forum/category/${categoryId}/subject/${subjectId}/messages")
    .body(StringBody("""{"content" : "message created"}"""))
    .check(status.is(200), 
        jsonPath("$._id").find.saveAs("messageId")
      ))
  .exec(http("Message Get")
    .get("/forum/category/${categoryId}/subject/${subjectId}/message/${messageId}")
    .check(status.is(200), 
        jsonPath("$._id").find.is("${messageId}"),
        jsonPath("$.content").find.is("message created")
      ))
  .exec(http("Message Update")
    .put("/forum/category/${categoryId}/subject/${subjectId}/message/${messageId}")
    .body(StringBody("""{"content" : "message updated"}"""))
    .check(status.is(200)))
  .exec(http("Message Get updated")
    .get("/forum/category/${categoryId}/subject/${subjectId}/message/${messageId}")
    .check(status.is(200), 
        jsonPath("$.content").find.is("message updated")
      ))
  .exec(http("Message List")
    .get("/forum/category/${categoryId}/subject/${subjectId}/messages")
    .check(status.is(200), 
        jsonPath("$[0]._id").find.is("${messageId}")
      ))
  .exec(http("Logout 1 - teacher")
    .get("""/auth/logout""")
    .check(status.is(302)))

  val scnNoRights =
  // No Share
  exec(http("Login 2 - student")
    .post("""/auth/login""")
    .formParam("""email""", """${studentLogin}""")
    .formParam("""password""", """blipblop""")
    .check(status.is(302)))
  // can
  .exec(http("Category List")
    .get("/forum/categories")
    .check(status.is(200)))
  // cant
  .exec(http("Category Get")
    .get("/forum/category/${categoryId}")
    .check(status.is(401)))
  .exec(http("Subject List")
    .get("/forum/category/${categoryId}/subjects")
    .check(status.is(401)))
   .exec(http("Subject Get")
    .get("/forum/category/${categoryId}/subject/${subjectId}")
    .check(status.is(401)))
  .exec(http("Message List")
    .get("/forum/category/${categoryId}/subject/${subjectId}/messages")
    .check(status.is(401)))
  .exec(http("Message Get")
    .get("/forum/category/${categoryId}/subject/${subjectId}/message/${messageId}")
    .check(status.is(401)))
  .exec(http("Subject Create")
    .post("/forum/category/${categoryId}/subjects")
    .body(StringBody("""{"title" : "cannot create subject"}"""))
    .check(status.is(401)))
  .exec(http("Message Create")
    .post("/forum/category/${categoryId}/subject/${subjectId}/messages")
    .body(StringBody("""{"content" : "cannot create message"}"""))
    .check(status.is(401)))
  .exec(http("Category Update")
    .put("/forum/category/${categoryId}")
    .body(StringBody("""{"name" : "cannot update category"}"""))
    .check(status.is(401)))
  .exec(http("Subject Update")
    .put("/forum/category/${categoryId}/subject/${subjectId}")
    .body(StringBody("""{"title" : "cannot update subject"}"""))
    .check(status.is(401)))
  .exec(http("Message Update")
    .put("/forum/category/${categoryId}/subject/${subjectId}/message/${messageId}")
    .body(StringBody("""{"content" : "message updated"}"""))
    .check(status.is(401)))
  .exec(http("Logout 2 - student")
    .get("""/auth/logout""")
    .check(status.is(302)))

  val scnRead =
  // Share Person - Read
  exec(http("Login 3 - teacher")
    .post("""/auth/login""")
    .formParam("""email""", """${teacherLogin}""")
    .formParam("""password""", """blipblop""")
    .check(status.is(302)))
  .exec(http("Get share json")
    .get("/forum/share/json/${categoryId}")
    .check(status.is(200)))
  .exec(http("Share Read permission with Student as a Person")
    .put("/forum/share/json/${categoryId}")
    .bodyPart(StringBodyPart("userId", "${studentId}"))
    .bodyPart(StringBodyPart("actions", "net-atos-entng-forum-controllers-ForumController|getSubject"))
    .bodyPart(StringBodyPart("actions", "net-atos-entng-forum-controllers-ForumController|getMessage"))
    .bodyPart(StringBodyPart("actions", "net-atos-entng-forum-controllers-ForumController|getCategory"))
    .bodyPart(StringBodyPart("actions", "net-atos-entng-forum-controllers-ForumController|listSubjects"))
    .bodyPart(StringBodyPart("actions", "net-atos-entng-forum-controllers-ForumController|listMessages"))
    .check(status.is(200)))
  .exec(http("Logout 3 - teacher")
    .get("""/auth/logout""")
    .check(status.is(302)))
  .exec(http("Login 4 - student")
    .post("""/auth/login""")
    .formParam("""email""", """${studentLogin}""")
    .formParam("""password""", """blipblop""")
    .check(status.is(302)))
  // can
  .exec(http("Category List")
    .get("/forum/categories")
    .check(status.is(200), 
        jsonPath("$[0]._id").find.is("${categoryId}")
      ))
  .exec(http("Category Get")
    .get("/forum/category/${categoryId}")
    .check(status.is(200), 
        jsonPath("$._id").find.is("${categoryId}")
      ))
  .exec(http("Subject List")
    .get("/forum/category/${categoryId}/subjects")
    .check(status.is(200), 
        jsonPath("$[0]._id").find.is("${subjectId}")
      ))
   .exec(http("Subject Get")
    .get("/forum/category/${categoryId}/subject/${subjectId}")
    .check(status.is(200), 
        jsonPath("$._id").find.is("${subjectId}")
      ))
  .exec(http("Message List")
    .get("/forum/category/${categoryId}/subject/${subjectId}/messages")
    .check(status.is(200), 
        jsonPath("$[0]._id").find.is("${messageId}")
      ))
  .exec(http("Message Get")
    .get("/forum/category/${categoryId}/subject/${subjectId}/message/${messageId}")
    .check(status.is(200), 
        jsonPath("$._id").find.is("${messageId}")
      ))
  // cant
  .exec(http("Subject Create")
    .post("/forum/category/${categoryId}/subjects")
    .body(StringBody("""{"title" : "cannot create subject"}"""))
    .check(status.is(401)))
  .exec(http("Message Create")
    .post("/forum/category/${categoryId}/subject/${subjectId}/messages")
    .body(StringBody("""{"content" : "cannot create message"}"""))
    .check(status.is(401)))
  .exec(http("Category Update")
    .put("/forum/category/${categoryId}")
    .body(StringBody("""{"name" : "cannot update category"}"""))
    .check(status.is(401)))
  .exec(http("Subject Update")
    .put("/forum/category/${categoryId}/subject/${subjectId}")
    .body(StringBody("""{"title" : "cannot update subject"}"""))
    .check(status.is(401)))
  .exec(http("Message Update")
    .put("/forum/category/${categoryId}/subject/${subjectId}/message/${messageId}")
    .body(StringBody("""{"content" : "message updated"}"""))
    .check(status.is(401)))
  .exec(http("Delete Category")
    .delete("/forum/category/${categoryId}")
    .check(status.is(401)))
  .exec(http("Delete Subject")
    .delete("/forum/category/${categoryId}/subject/${subjectId}")
    .check(status.is(401)))
  .exec(http("Delete Message")
    .delete("/forum/category/${categoryId}/subject/${subjectId}/message/${messageId}")
    .check(status.is(401)))
  .exec(http("Logout 4 - student")
    .get("""/auth/logout""")
    .check(status.is(302)))

  val scnContrib =
  // Share Person - Contrib
  exec(http("Login 5 - teacher")
    .post("""/auth/login""")
    .formParam("""email""", """${teacherLogin}""")
    .formParam("""password""", """blipblop""")
    .check(status.is(302)))
  .exec(http("Share Contrib permission with Student as a Person")
    .put("/forum/share/json/${categoryId}")
    .bodyPart(StringBodyPart("userId", "${studentId}"))
    .bodyPart(StringBodyPart("actions", "net-atos-entng-forum-controllers-ForumController|createMessage"))
    .check(status.is(200)))
  .exec(http("Logout 5 - teacher")
    .get("""/auth/logout""")
    .check(status.is(302)))
  .exec(http("Login 6 - student")
    .post("""/auth/login""")
    .formParam("""email""", """${studentLogin}""")
    .formParam("""password""", """blipblop""")
    .check(status.is(302)))
  // can
  .exec(http("Category List")
    .get("/forum/categories")
    .check(status.is(200), 
        jsonPath("$[0]._id").find.is("${categoryId}")
      ))
  .exec(http("Category Get")
    .get("/forum/category/${categoryId}")
    .check(status.is(200), 
        jsonPath("$._id").find.is("${categoryId}")
      ))
  .exec(http("Subject List")
    .get("/forum/category/${categoryId}/subjects")
    .check(status.is(200), 
        jsonPath("$[0]._id").find.is("${subjectId}")
      ))
   .exec(http("Subject Get")
    .get("/forum/category/${categoryId}/subject/${subjectId}")
    .check(status.is(200), 
        jsonPath("$._id").find.is("${subjectId}")
      ))
  .exec(http("Message List")
    .get("/forum/category/${categoryId}/subject/${subjectId}/messages")
    .check(status.is(200), 
        jsonPath("$[0]._id").find.is("${messageId}")
      ))
  .exec(http("Message Get")
    .get("/forum/category/${categoryId}/subject/${subjectId}/message/${messageId}")
    .check(status.is(200), 
        jsonPath("$._id").find.is("${messageId}")
      ))
  .exec(http("Message Create")
    .post("/forum/category/${categoryId}/subject/${subjectId}/messages")
    .body(StringBody("""{"content" : "student contrib message created"}"""))
    .check(status.is(200), 
        jsonPath("$._id").find.saveAs("messageStudentContribId")
      ))
  // can : update my message
  .exec(http("Message Update (my)")
    .put("/forum/category/${categoryId}/subject/${subjectId}/message/${messageStudentContribId}")
    .body(StringBody("""{"content" : "student contrib message updated"}"""))
    .check(status.is(200)))
  .exec(http("Message Get updated (my)")
    .get("/forum/category/${categoryId}/subject/${subjectId}/message/${messageStudentContribId}")
    .check(status.is(200), 
        jsonPath("$.content").find.is("student contrib message updated")
      ))
  // cant
  .exec(http("Subject Create")
    .post("/forum/category/${categoryId}/subjects")
    .body(StringBody("""{"title" : "cannot create subject"}"""))
    .check(status.is(401)))
  .exec(http("Category Update")
    .put("/forum/category/${categoryId}")
    .body(StringBody("""{"name" : "cannot update category"}"""))
    .check(status.is(401)))
  .exec(http("Subject Update")
    .put("/forum/category/${categoryId}/subject/${subjectId}")
    .body(StringBody("""{"title" : "cannot update subject"}"""))
    .check(status.is(401)))
  // cant : update others message
  .exec(http("Message Update (others)")
    .put("/forum/category/${categoryId}/subject/${subjectId}/message/${messageId}")
    .body(StringBody("""{"content" : "student contrib others message updated"}"""))
    .check(status.is(401)))
  .exec(http("Delete Message")
    .delete("/forum/category/${categoryId}/subject/${subjectId}/message/${messageId}")
    .check(status.is(401)))
  .exec(http("Logout 6 - student")
    .get("""/auth/logout""")
    .check(status.is(302)))

  val scnModerate =
  // Share Person - Moderate (Publish)
  exec(http("Login 7 - teacher")
    .post("""/auth/login""")
    .formParam("""email""", """${teacherLogin}""")
    .formParam("""password""", """blipblop""")
    .check(status.is(302)))
  .exec(http("Share Contrib permission with Student as a Person")
    .put("/forum/share/json/${categoryId}")
    .bodyPart(StringBodyPart("userId", "${studentId}"))
    .bodyPart(StringBodyPart("actions", "net-atos-entng-forum-controllers-ForumController|updateMessage"))
    .bodyPart(StringBodyPart("actions", "net-atos-entng-forum-controllers-ForumController|deleteSubject"))
    .bodyPart(StringBodyPart("actions", "net-atos-entng-forum-controllers-ForumController|updateSubject"))
    .bodyPart(StringBodyPart("actions", "net-atos-entng-forum-controllers-ForumController|createSubject"))
    .bodyPart(StringBodyPart("actions", "net-atos-entng-forum-controllers-ForumController|deleteMessage"))
    .check(status.is(200)))
  .exec(http("Logout 7 - teacher")
    .get("""/auth/logout""")
    .check(status.is(302)))
  .exec(http("Login 8 - student")
    .post("""/auth/login""")
    .formParam("""email""", """${studentLogin}""")
    .formParam("""password""", """blipblop""")
    .check(status.is(302)))
  // can
  .exec(http("Category List")
    .get("/forum/categories")
    .check(status.is(200), 
        jsonPath("$[0]._id").find.is("${categoryId}")
      ))
  .exec(http("Category Get")
    .get("/forum/category/${categoryId}")
    .check(status.is(200), 
        jsonPath("$._id").find.is("${categoryId}")
      ))
  .exec(http("Subject List")
    .get("/forum/category/${categoryId}/subjects")
    .check(status.is(200), 
        jsonPath("$[0]._id").find.is("${subjectId}")
      ))
   .exec(http("Subject Get")
    .get("/forum/category/${categoryId}/subject/${subjectId}")
    .check(status.is(200), 
        jsonPath("$._id").find.is("${subjectId}")
      ))
  .exec(http("Message List")
    .get("/forum/category/${categoryId}/subject/${subjectId}/messages")
    .check(status.is(200), 
        jsonPath("$[0]._id").find.is("${messageId}")
      ))
  .exec(http("Message Get")
    .get("/forum/category/${categoryId}/subject/${subjectId}/message/${messageId}")
    .check(status.is(200), 
        jsonPath("$._id").find.is("${messageId}")
      ))
  .exec(http("Subject Create")
    .post("/forum/category/${categoryId}/subjects")
    .body(StringBody("""{"title" : "subject student moderate created"}"""))
    .check(status.is(200), 
        jsonPath("$._id").find.saveAs("subjectStudentModerateId")
      ))
  .exec(http("Subject Update")
    .put("/forum/category/${categoryId}/subject/${subjectStudentModerateId}")
    .body(StringBody("""{"title" : "subject student moderate updated"}"""))
    .check(status.is(200)))
  .exec(http("Subject Get updated")
    .get("/forum/category/${categoryId}/subject/${subjectStudentModerateId}")
    .check(status.is(200), 
        jsonPath("$.title").find.is("subject student moderate updated")
      ))
  .exec(http("Message Create")
    .post("/forum/category/${categoryId}/subject/${subjectId}/messages")
    .body(StringBody("""{"content" : "student moderator message created"}"""))
    .check(status.is(200), 
        jsonPath("$._id").find.saveAs("messageStudentModerateId")
      ))
  // can : update my message
  .exec(http("Message Update (my)")
    .put("/forum/category/${categoryId}/subject/${subjectId}/message/${messageStudentModerateId}")
    .body(StringBody("""{"content" : "student moderator message updated"}"""))
    .check(status.is(200)))
  .exec(http("Message Get updated (my)")
    .get("/forum/category/${categoryId}/subject/${subjectId}/message/${messageStudentModerateId}")
    .check(status.is(200), 
        jsonPath("$.content").find.is("student moderator message updated")
      ))
  .exec(http("Delete Message")
    .delete("/forum/category/${categoryId}/subject/${subjectId}/message/${messageStudentModerateId}")
    .check(status.is(200)))
  // can : update others message
  .exec(http("Message Update (others)")
    .put("/forum/category/${categoryId}/subject/${subjectId}/message/${messageId}")
    .body(StringBody("""{"content" : "student moderator others message updated"}"""))
    .check(status.is(200)))
  // cant
  .exec(http("Category Update")
    .put("/forum/category/${categoryId}")
    .body(StringBody("""{"name" : "cannot update category"}"""))
    .check(status.is(401)))
  .exec(http("Delete Category")
    .delete("/forum/category/${categoryId}")
    .check(status.is(401)))
  .exec(http("Logout 8 - student")
    .get("""/auth/logout""")
    .check(status.is(302)))

  val scnManage =
  // Share Person - Moderate (Publish)
  exec(http("Login 9 - teacher")
    .post("""/auth/login""")
    .formParam("""email""", """${teacherLogin}""")
    .formParam("""password""", """blipblop""")
    .check(status.is(302)))
  .exec(http("Share Contrib permission with Student as a Person")
    .put("/forum/share/json/${categoryId}")
    .bodyPart(StringBodyPart("userId", "${studentId}"))
    .bodyPart(StringBodyPart("actions", "net-atos-entng-forum-controllers-ForumController|updateCategory"))
    .bodyPart(StringBodyPart("actions", "net-atos-entng-forum-controllers-ForumController|shareCategory"))
    .bodyPart(StringBodyPart("actions", "net-atos-entng-forum-controllers-ForumController|shareCategorySubmit"))
    .bodyPart(StringBodyPart("actions", "net-atos-entng-forum-controllers-ForumController|deleteCategory"))
    .bodyPart(StringBodyPart("actions", "net-atos-entng-forum-controllers-ForumController|removeShareCategory"))
    .check(status.is(200)))
  .exec(http("Logout 9 - teacher")
    .get("""/auth/logout""")
    .check(status.is(302)))
  .exec(http("Login 10 - student")
    .post("""/auth/login""")
    .formParam("""email""", """${studentLogin}""")
    .formParam("""password""", """blipblop""")
    .check(status.is(302)))
  // can
  .exec(http("Category List")
    .get("/forum/categories")
    .check(status.is(200), 
        jsonPath("$[0]._id").find.is("${categoryId}")
      ))
  .exec(http("Category Get")
    .get("/forum/category/${categoryId}")
    .check(status.is(200), 
        jsonPath("$._id").find.is("${categoryId}")
      ))
  .exec(http("Subject List")
    .get("/forum/category/${categoryId}/subjects")
    .check(status.is(200), 
        jsonPath("$[0]._id").find.is("${subjectId}")
      ))
   .exec(http("Subject Get")
    .get("/forum/category/${categoryId}/subject/${subjectId}")
    .check(status.is(200), 
        jsonPath("$._id").find.is("${subjectId}")
      ))
  .exec(http("Message List")
    .get("/forum/category/${categoryId}/subject/${subjectId}/messages")
    .check(status.is(200), 
        jsonPath("$[0]._id").find.is("${messageId}")
      ))
  .exec(http("Message Get")
    .get("/forum/category/${categoryId}/subject/${subjectId}/message/${messageId}")
    .check(status.is(200), 
        jsonPath("$._id").find.is("${messageId}")
      ))
  .exec(http("Subject Create")
    .post("/forum/category/${categoryId}/subjects")
    .body(StringBody("""{"title" : "subject student moderate created"}"""))
    .check(status.is(200), 
        jsonPath("$._id").find.saveAs("subjectStudentManagerId")
      ))
  .exec(http("Subject Update")
    .put("/forum/category/${categoryId}/subject/${subjectStudentManagerId}")
    .body(StringBody("""{"title" : "subject student moderate updated"}"""))
    .check(status.is(200)))
  .exec(http("Subject Get updated")
    .get("/forum/category/${categoryId}/subject/${subjectStudentManagerId}")
    .check(status.is(200), 
        jsonPath("$.title").find.is("subject student moderate updated")
      ))
  .exec(http("Message Create")
    .post("/forum/category/${categoryId}/subject/${subjectId}/messages")
    .body(StringBody("""{"content" : "student manager message created"}"""))
    .check(status.is(200), 
        jsonPath("$._id").find.saveAs("messageStudentManagerId")
      ))
  // can : update my message
  .exec(http("Message Update (my)")
    .put("/forum/category/${categoryId}/subject/${subjectId}/message/${messageStudentManagerId}")
    .body(StringBody("""{"content" : "student manager message updated"}"""))
    .check(status.is(200)))
  .exec(http("Message Get updated (my)")
    .get("/forum/category/${categoryId}/subject/${subjectId}/message/${messageStudentManagerId}")
    .check(status.is(200), 
        jsonPath("$.content").find.is("student manager message updated")
      ))
  .exec(http("Delete Message")
    .delete("/forum/category/${categoryId}/subject/${subjectId}/message/${messageStudentManagerId}")
    .check(status.is(200)))
  // can : update others message
  .exec(http("Message Update (others)")
    .put("/forum/category/${categoryId}/subject/${subjectId}/message/${messageId}")
    .body(StringBody("""{"content" : "student manage others message updated"}"""))
    .check(status.is(200)))
  // Delete
  .exec(http("Delete Message")
    .delete("/forum/category/${categoryId}/subject/${subjectId}/message/${messageId}")
    .check(status.is(200)))
  .exec(http("Get Message deleted")
    .get("/forum/category/${categoryId}/subject/${subjectId}/message/${messageId}")
    .check(status.is(404)))
  .exec(http("Delete Subject")
    .delete("/forum/category/${categoryId}/subject/${subjectId}")
    .check(status.is(200)))
  .exec(http("Get Subject deleted")
    .get("/forum/category/${categoryId}/subject/${subjectId}")
    .check(status.is(404)))
  .exec(http("Delete My Subject") // to cleanup
    .delete("/forum/category/${categoryId}/subject/${subjectStudentModerateId}")
    .check(status.is(200)))
  .exec(http("Delete Category")
    .delete("/forum/category/${categoryId}")
    .check(status.is(200)))
  .exec(http("Get Category deleted")
    .get("/forum/category/${categoryId}")
    .check(status.is(401))) // sould SharedAndOwner Filter let pass and return 404 ?
}